### ISSUE TITLE
Members and Admins sections of state are not populated when a group is created

### ISSUE THREAD

**Issue by iamjarvo** [vinyldns/terraform-provider-vinyldns#32]
```
provider "vinyldns" {
}

resource "vinyldns_group" "admin_group" {
  name = "admin-group"
  email = "user@vinyl.com"
}
```

After ^ is run successfully parts of admin and member are not saved in the state

```
 ~ vinyldns_group.admin_group
      admin.#:                     "1" => "0"
      admin.321395458.email:       "" => ""
      admin.321395458.first_name:  "" => ""
      admin.321395458.id:          "123" => ""
      admin.321395458.last_name:   "" => ""
      admin.321395458.user_name:   "" => ""
      member.#:                    "1" => "0"
      member.321395458.email:      "" => ""
      member.321395458.first_name: "" => ""
      member.321395458.id:         "123" => ""
      member.321395458.last_name:  "" => ""
      member.321395458.user_name:  "" => ""
```

**Comment by mdb** [comment]
@iamjarvo I'm a bit confused about your example, as your `vinyldns_group.admin_group` has no `admin` or `member` members. Are there Step 0 -> Step n steps missing from your flow? If so, could you provide more detailed outline of how one can reproduce this from scratch? Thanks!

**Comment by iamjarvo** [comment]
Did some follow up on this.

By default vinyl will use current user for admins and members. Vinyl only gives the id of the users when returning a group. Getting a more detailed view of a user requires another all to `/groups/{groupId}/members`. This is what a group response looks like

```
{
  "id": "6f8afcda-7529-4cad-9f2d-76903f4b1aca",
  "name": "some-group",
  "email": "test@example.com",
  "created": "2017-03-02T15:29:21Z",
  "status": "Active",
  "members": [
    {
      "id": "2764183c-5e75-4ae6-8833-503cd5f4dcb0"
    },
    {
      "id": "c8630ebc-0af2-4c9a-a0a0-d18c590ed03e"
    }
  ],
  "admins": [
    {
      "id": "2764183c-5e75-4ae6-8833-503cd5f4dcb0"
    }
  ]
}
```

Doesn't seem like having detailed info about users in the group beyond ID add much value. 

2 options:

1) we only use the ID attribute
2) We make an extra call to get members and set all the fields

**Comment by mdb** [comment]
@iamjarvo Thanks for this! This confuses me, as I would expect the following to account for this scenario if, as you say, the groups response contains record of the `members` and `admins`:

https://github.com/vinyldns/terraform-provider-vinyldns/blob/master/vinyldns/resource_group.go#L80-L94

So, again...

Are there Step 0 -> Step n steps missing from your "how to reproduce this" flow? If so, could you provide more detailed outline of how one can reproduce this from scratch?

**Comment by mdb** [comment]
After discussing with @iamjarvo , I now understand...

1. terraform apply the following:
```hcl
resource "vinyldns_group" "admin_group" {
  name = "admin-group"
  email = "user@vinyl.com"
}
```
2. Get resulting state that contains the members and admins (albeit only their IDs) returned by the VInylDNS API, as VinylDNS will automatically assign `members` and `admins` membership IDs of the user with whom the API credentials are associated.
3. Perform a subsequent `terraform plan`
resource "vinyldns_group" "admin_group" {
  name = "admin-group"
  email = "user@vinyl.com"
}
```
4. Observe that this seeks to delete the members and admins from the state, as it forms an API request based on the HCL.

A potential solution is to change `member {}` and `admin {}` to required `member_ids = []` and `admin_ids = []` arguments.
