### ISSUE TITLE
Default description for Group description

### ISSUE THREAD

**Issue by iamjarvo** [vinyldns/terraform-provider-vinyldns#33]
In the aws provider the default description for some resources is `Managed by Terraform`.
https://github.com/terraform-providers/terraform-provider-aws/blob/502420d48609b4b72cd76dd74b155a09e2367d18/aws/resource_aws_security_group.go#L62

Would be great to have this for the vinyl group description

**Comment by mdb** [comment]
Thanks @iamjarvo ! I think it's also worth researching whether other VinylDNS resources support a `description` and doing the same for these.
