### ISSUE TITLE
Treat missing resources as a create and not a 404

### ISSUE THREAD

**Issue by iamjarvo** [vinyldns/terraform-provider-vinyldns#34]
Currently the provider will return a 404 when a resource does not exist in vinyl but exists in state. The AWS provider handles this by checking if there is a 404 from the API and treats it as a create. 

Here is an example:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_s3_bucket.go#L767-L770

**Comment by mdb** [comment]
Thanks @iamjarvo ! Good catch. 

To put a slightly finer point on this, imagine the following scenario...
1. user `terraform apply`s to create resource `foo`
2. resource `foo` is destroyed outside of Terraform
3. subsequent `terraform plan`/`apply`s error, as `foo`'s `Read` callback encounters a 404 attempting to fetch `foo`, despite that it lives in tfstate
4. the user is stuck in this state unless tfstate is modified to remove record of `foo`

I believe the correct course of action is to modify resource `Read` callbacks such that if an attempt to `GET` the resource from its provider API yields a 404, we clear state via `d.SetId("")` and return `nil` from the `Read` callback. In turn, this prompts Terraform to believe a fresh `Create` is necessary. This appears to be a pattern employed throughout the AWS provider, though it may be worth noting the extent to which this is _the_ correct pattern to always employ.

Pseudo code illustrating the presumed correct, desired behavior @iamjarvo is describing:

```golang
func resourceFooRead(d *schema.ResourceData, meta interface{}) error {
  r, err := meta.(*vinyldns.Client).Foo(d.Id())

  if err != nil {
    if dErr, ok := err.(*vinyldns.Error); ok {
      if dErr.ResponseCode == http.StatusNotFound {
        log.Printf("[WARN] foo (%s) not found, error code (404)", d.Id())

        d.SetId("")

        return nil
      }

      return fmt.Errorf("error reading foo (%s): %s", d.Id(), err)
    }

    return fmt.Errorf("error reading foo (%s): %s", d.Id(), err)
  }
  ...
}
```

```

**Comment by mdb** [comment]
@iamjarvo Also, I _believe_ this is a repeat of issue #27, which I previously overlooked. I'll close issue #27 in favor of this.
