### ISSUE TITLE
Create a Terraform 0.12.x compatible release

### ISSUE THREAD

**Issue by mattamizer** [vinyldns/terraform-provider-vinyldns#50]
Currently, the latest available release is complied against a 0.11.x version of Terraform. When trying to upgrade to Terraform 0.12.x we are presented with the following error:
`Error: failed to load provider “vinyldns”: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]`

The fix would be to release a version of the vinyldns provider which is complied against Terraform 0.12.x as it does not seem to want any non 0.12.x providers if you upgrade.

**Comment by mdb** [comment]
@mattamizer Thanks for this! I created a [0.9.1rc-tf-0.12 prerelease](https://github.com/vinyldns/terraform-provider-vinyldns/releases/tag/0.9.1rc-tf-0.12) to test.

1. Does this work as expected with Terraform 0.12?
2. Does this work as expected with Terraform 0.11?
3. Are there any issue #47 things we can also tackle based on your learnings?

Thanks!

**Comment by mattamizer** [comment]
@mdb I was able to test point 2 and confirm that things work as expected. I will test point 1 once I get the cycles to do so and I'll look at #47 now and update with anything I can.

**Comment by mdb** [comment]
@mattamizer Great - thanks so much. From my own testing, the answers to both questions 1 & 2 are "Yes, everything appears to work as expected." I'm hoping to ship an official 0.9.1 release tomorrow.

**Comment by mattamizer** [comment]
That's great news! Keep me posted and let me know if I can help in any way.
