### ISSUE TITLE
Importing resources fails with a non descriptive error

### ISSUE THREAD

**Issue by mattamizer** [vinyldns/terraform-provider-vinyldns#92]
When running a `terraform import` using what I believe to be the correct format the provider gives back the following error and the import fails.
```
Error: error reading recordset (c368d394-c1bc-4dd0-9b3a-16f589ffb4e8): Get /zones/<zone_id>/recordsets/<record_set_id>: unsupported protocol scheme ""
```
The command that was run was
```
terraform import -var-file=client.tfvars.json -var-file=backend.tfvars module.base.vinyldns_record_set.promxy-record-set <zond_id>:<record_set_Id>
```

**Comment by mdb** [comment]
@mattamizer Thanks for reporting this. Is it possible that you did not have a `VINYLDNS_HOST` environment variable specifying a VinylDNS API URL?

**Comment by mattamizer** [comment]
@mdb I'll take a look on Monday as that may be the case, but I'm pretty sure I exported that.

**Comment by mattamizer** [comment]
@mdb you were right, that VAR is currently unset. I'll set it and try again. If the error goes away I'll close the issue.

**Comment by mattamizer** [comment]
Worked like a charm. Closing.
